# Generated by Django 5.1.3 on 2024-12-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instrumentType',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='musician',
            name='phoneNo',
            field=models.CharField(max_length=15),
        ),
    ]
